/**
 * generated by Xtext 2.10.0
 */
package de.tu_bs.cs.isf.cbc.textual.tool.ui;

import de.tu_bs.cs.isf.cbc.textual.tool.ui.AbstractDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DslUiModule extends AbstractDslUiModule {
  public DslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
