/*
 * generated by Xtext 2.10.0
 */
package de.tu_bs.cs.isf.cbc.textual.tool.ui;

import com.google.inject.Injector;
import de.tu_bs.cs.isf.cbc.textual.tool.ui.internal.ToolActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ToolActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ToolActivator.getInstance().getInjector(ToolActivator.DE_TU_BS_CS_ISF_CBC_TEXTUAL_TOOL_DSL);
	}
	
}
