/**
 */
package de.tu_bs.cs.isf.taxonomy.model.taxonomy.provider;

import de.tu_bs.cs.isf.taxonomy.model.taxonomy.util.TaxonomyAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class TaxonomyItemProviderAdapterFactory extends TaxonomyAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public TaxonomyItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.Taxonomy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TaxonomyItemProvider taxonomyItemProvider;

	/**
	 * This creates an adapter for a {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.Taxonomy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTaxonomyAdapter() {
		if (taxonomyItemProvider == null) {
			taxonomyItemProvider = new TaxonomyItemProvider(this);
		}

		return taxonomyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.Algorithm} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AlgorithmItemProvider algorithmItemProvider;

	/**
	 * This creates an adapter for a {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.Algorithm}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAlgorithmAdapter() {
		if (algorithmItemProvider == null) {
			algorithmItemProvider = new AlgorithmItemProvider(this);
		}

		return algorithmItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.DataStructure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataStructureItemProvider dataStructureItemProvider;

	/**
	 * This creates an adapter for a {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.DataStructure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataStructureAdapter() {
		if (dataStructureItemProvider == null) {
			dataStructureItemProvider = new DataStructureItemProvider(this);
		}

		return dataStructureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.Method} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MethodItemProvider methodItemProvider;

	/**
	 * This creates an adapter for a {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.Method}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMethodAdapter() {
		if (methodItemProvider == null) {
			methodItemProvider = new MethodItemProvider(this);
		}

		return methodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.DataType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataTypeItemProvider dataTypeItemProvider;

	/**
	 * This creates an adapter for a {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.DataType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataTypeAdapter() {
		if (dataTypeItemProvider == null) {
			dataTypeItemProvider = new DataTypeItemProvider(this);
		}

		return dataTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.GlobalConditions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GlobalConditionsItemProvider globalConditionsItemProvider;

	/**
	 * This creates an adapter for a {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.GlobalConditions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGlobalConditionsAdapter() {
		if (globalConditionsItemProvider == null) {
			globalConditionsItemProvider = new GlobalConditionsItemProvider(this);
		}

		return globalConditionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.Condition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConditionItemProvider conditionItemProvider;

	/**
	 * This creates an adapter for a {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.Condition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConditionAdapter() {
		if (conditionItemProvider == null) {
			conditionItemProvider = new ConditionItemProvider(this);
		}

		return conditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.JavaVariables} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JavaVariablesItemProvider javaVariablesItemProvider;

	/**
	 * This creates an adapter for a {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.JavaVariables}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJavaVariablesAdapter() {
		if (javaVariablesItemProvider == null) {
			javaVariablesItemProvider = new JavaVariablesItemProvider(this);
		}

		return javaVariablesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.JavaVariable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JavaVariableItemProvider javaVariableItemProvider;

	/**
	 * This creates an adapter for a {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.JavaVariable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJavaVariableAdapter() {
		if (javaVariableItemProvider == null) {
			javaVariableItemProvider = new JavaVariableItemProvider(this);
		}

		return javaVariableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.Renaming} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RenamingItemProvider renamingItemProvider;

	/**
	 * This creates an adapter for a {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.Renaming}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRenamingAdapter() {
		if (renamingItemProvider == null) {
			renamingItemProvider = new RenamingItemProvider(this);
		}

		return renamingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.Rename} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RenameItemProvider renameItemProvider;

	/**
	 * This creates an adapter for a {@link de.tu_bs.cs.isf.taxonomy.model.taxonomy.Rename}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRenameAdapter() {
		if (renameItemProvider == null) {
			renameItemProvider = new RenameItemProvider(this);
		}

		return renameItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (taxonomyItemProvider != null) taxonomyItemProvider.dispose();
		if (algorithmItemProvider != null) algorithmItemProvider.dispose();
		if (dataStructureItemProvider != null) dataStructureItemProvider.dispose();
		if (methodItemProvider != null) methodItemProvider.dispose();
		if (dataTypeItemProvider != null) dataTypeItemProvider.dispose();
		if (globalConditionsItemProvider != null) globalConditionsItemProvider.dispose();
		if (conditionItemProvider != null) conditionItemProvider.dispose();
		if (javaVariablesItemProvider != null) javaVariablesItemProvider.dispose();
		if (javaVariableItemProvider != null) javaVariableItemProvider.dispose();
		if (renamingItemProvider != null) renamingItemProvider.dispose();
		if (renameItemProvider != null) renameItemProvider.dispose();
	}

}
