# This workflow will build a Java project with Maven.

name: Java CI with Maven

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -U clean compile

  format:
    runs-on: ubuntu-latest
    steps:
    - name: Check Format
      run: mvn com.diffplug.spotless:spotless-maven-plugin:2.44.0:check