# This workflow will build a Java project with Maven.

name: Java CI with Maven

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
  push:
    branches: [ "master" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Apply Format
      run: mvn spotless:apply

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn compile
    - name: Clean
      run: mvn clean
